### PR TITLE
luci-base: Allow "*" (== Any zone) in the firewall zone selection.

### LINKED ISSUE #7591: luci-app-firewall: cannot choose `Any zone` in `Output zone` field | temporary fix found
### Is there an existing issue for this?

- [x] I have searched among all existing issues (including closed issues)

### screenshots or captures

Hello!

I have just build and installed a fresh firmware from the `master`/`main` branch and faced with an issue: I cannot add or modify a firewall rule and set `Output zone` to `Any zone`: LuCI shows an error: `Expecting: valid UCI identifier`. Please refer to the attached screenshot for more details.

It is possible to modify the rule via editing the config file, but that's not very convenient.

I have searched the similar issues and found this: https://github.com/openwrt/luci/issues/7563
I believe my issue might be connected with it.

### **UPD - temporary fix:**
Quick and dirty fix for a live system - thanks to @systemcrash post here: https://github.com/openwrt/luci/issues/7563#issuecomment-2590229918

1. SSH to the router
2. Edit file /www/luci-static/resources/tools/widgets.js, e.x. `nano /www/luci-static/resources/tools/widgets.js`
3. Delete the following substring: `datatype:L.hasSystemFeature('firewall4')?(this.multiple?'list(uciname)':'uciname'):this.multiple?'list(and(uciname,maxlength(11)))':'and(uciname,maxlength(11))',`
4. Save file (ctrl+o).
5. Refresh the LuCI interface.
6. Done. This fix should work until a better and permanent solution is introduced.

Image

### Actual behaviour

When adding or modifying a firewall rule it is impossible to set `Output zone` field to `Any zone` value. LuCI shows an error: `Expecting: valid UCI identifier`.

### Expected behaviour

When adding or modifying a firewall rule it is possible to set `Output zone` field to `Any zone` value. LuCI accepts the value and saves it in the config file without any errors.

### Steps to reproduce

1. Obtain a freshly built (preferably based on `master`/`main` branch) firmware and install it.
2. Log in into LuCI.
3. Navigate to Network -> Firewall -> Traffic rules.
4. Add a new rule and set `Output zone` field to `Any zone`.
5. Observe the issue: LuCI highlights the value with red and shows `Expecting: valid UCI identifier` error. It is impossible to save the rule

### Additional Information

```shell
{
        "kernel": "6.6.74",
        "hostname": "router",
        "system": "ARMv8 Processor rev 0",
        "model": "Bananapi BPI-R4",
        "board_name": "bananapi,bpi-r4",
        "rootfs_type": "squashfs",
        "release": {
                "distribution": "OpenWrt",
                "version": "SNAPSHOT",
                "revision": "r28724-807074309d",
                "target": "mediatek/filogic",
                "description": "OpenWrt SNAPSHOT r28724-807074309d",
                "builddate": "1738094344"
        }
}
```

### What browsers do you see the problem on?

Firefox

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by adelton**
- [x] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [x] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [x] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [ ] Tested on: x86_64 VM with OpenWrt 24.10.0-rc7 (r28417-daef29c75d)
- [ ] \( Preferred ) Mention: @ the original code author for feedback
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [x] \( Optional ) Closes #7591
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [x] Description: followup to #7564, allowing a verbatim `*` for Any zone.

### CODE REVIEW

File: modules/luci-base/htdocs/luci-static/resources/tools/widgets.js [hunk 1]
```diff
@@ -149,8 +149,8 @@ var CBIZoneSelect = form.ListValue.extend({
 			dropdown_items: this.dropdown_size || this.size || 5,
 			validate: L.bind(this.validate, this, section_id),
 			datatype: L.hasSystemFeature('firewall4')
-				? ( this.multiple ? 'list(uciname)' : 'uciname' )
-				: this.multiple ? 'list(and(uciname,maxlength(11)))' : 'and(uciname,maxlength(11))',
+				? ( this.multiple ? 'list(or(uciname,"*"))' : 'or(uciname,"*")' )
+				: this.multiple ? 'list(or(and(uciname,maxlength(11)),"*"))' : 'or(and(uciname,maxlength(11)),"*")',
```
Comment (this-username-has-been-taken) [inline modules/luci-base/htdocs/luci-static/resources/tools/widgets.js:153]: I'd suggest putting the "else" part under parentheses too to make it look uniform: `: ( this.multiple ? 'list(or(and(uciname,maxlength(11)),"*"))' : 'or(and(uciname,maxlength(11)),"*")' ),`
But that's not critical/

**Comment by this-username-has-been-taken** [comment]
Tested on a live system. The fix works.

File: modules/luci-base/htdocs/luci-static/resources/tools/widgets.js (hunk 1 above)
Comment (adelton) [reply modules/luci-base/htdocs/luci-static/resources/tools/widgets.js:153]: That would be a separate change for different PR. I'd like to keep this PR focused at the issue at hand, to make reviews easier.

**Review by this-username-has-been-taken — APPROVED** [review]

**Comment by this-username-has-been-taken** [comment]
Thank you very much for a quick fix!!! :)
