### PR TITLE
luci-mod-network: Evidently hostid was not max 32 bits but 64 bits 🤷

### LINKED ISSUE #6714: Bug in IPv6-Suffix (hex) max 8 characters
Someone incorrectly limited the suffix length to 8 characters instead of 16.
https://github.com/openwrt/luci/commit/8bcca3452deb0206b04eac60146ec3e56ecf4801

Suffix was fixed after version 19.10 with a 64 bit value and it worked fine until 23.05.0 and after upgrading to 23.05.2 the suffix field is red now.

so.datatype = 'and(rangelength(0,8),hexstring)';
whould be
so.datatype = 'and(rangelength(0,16),hexstring)';

https://forum.openwrt.org/t/bug-in-ipv6-suffix-hex-max-8-characters/178274

### PR DESCRIPTION
**Pull request by systemcrash**
Should fix #6714

### CODE REVIEW

**Comment by systemcrash** [comment]
Needs picking to 23.05 branch

File: modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js [hunk 1]
```diff
@@ -910,7 +910,7 @@ return view.extend({
 		so = ss.option(form.Value, 'hostid',
 			_('IPv6-Suffix (hex)'),
 			_('The IPv6 interface identifier (address suffix) as hexadecimal number (max. 8 chars).'));
```
Comment (dave14305) [inline modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js:912]: Please update the help text also. Thanks for jumping on this so quickly!

**Review by dave14305 — APPROVED** [review]

**Comment by systemcrash** [comment]
Please remember to pick to 23.x branch @jow-  😄
